/* ═══════════════════════════════════════════════════════════════════
   js/data.js
   ───────────────────────────────────────────────────────────────────
   WHAT THIS FILE DOES:
   Reads from window.MSM_DATA (built by admin-control/index.js)
   and populates every page section in the DOM.

   ── DO NOT EDIT THIS FILE TO CHANGE CONTENT ──
   Edit content in: admin-control/pages/*.js
   Edit images in:  admin-control/other/images.js
   Edit passwords:  admin-control/other/passwords.js
   ───────────────────────────────────────────────────────────────────
   ARCHITECTURE:
   · window.MSM  = the public API (all functions callable by main.js)
   · D           = shorthand for window.MSM_DATA
   · All render functions are called once on DOMContentLoaded
   · Page-specific renders are called lazily when page becomes active
═══════════════════════════════════════════════════════════════════ */

(function () {
  'use strict';

  /* ══════════════════════════════════════════════════════════════════
     GUARD — if admin-control files didn't load, abort gracefully.
  ══════════════════════════════════════════════════════════════════ */
  if (!window.MSM_DATA) {
    console.warn('[MSM data.js] window.MSM_DATA not found. ' +
      'Make sure admin-control scripts load before data.js in index.html.');
    window.MSM_DATA = {};
  }

  /* Shorthand — used everywhere in this file */
  var D = window.MSM_DATA;

  /* ══════════════════════════════════════════════════════════════════
     UTILITY HELPERS
  ══════════════════════════════════════════════════════════════════ */

  /** Get DOM element by ID. Returns null silently if not found. */
  function el(id) { return document.getElementById(id); }

  /** Get first matching element. Returns null silently. */
  function qs(selector) { return document.querySelector(selector); }

  /** Get all matching elements as array. */
  function qsa(selector) { return Array.from(document.querySelectorAll(selector)); }

  /** Set innerHTML safely — only if element exists. */
  function setHTML(id, html) {
    var element = el(id);
    if (element) element.innerHTML = html;
  }

  /** Set textContent safely — only if element exists. */
  function setText(id, text) {
    var element = el(id);
    if (element) element.textContent = text;
  }

  /**
   * Build a list-item HTML string for lists/projects pages.
   * @param {number} num    - item number (01, 02...)
   * @param {string} title  - item title
   * @param {string} meta   - item meta text
   * @param {string} status - status key (seen/want/completed/etc.)
   * @param {string} label  - badge label text
   */
  function buildListItem(num, title, meta, status, label) {
    var numStr = num < 10 ? '0' + num : '' + num;
    return [
      '<div class="list-item">',
        '<div class="list-item-num">' + numStr + '</div>',
        '<div class="list-item-info">',
          '<div class="list-item-title">' + escapeHTML(title) + '</div>',
          '<div class="list-item-meta">'  + escapeHTML(meta)  + '</div>',
        '</div>',
        '<span class="list-item-status status-' + status + '">' + escapeHTML(label) + '</span>',
      '</div>'
    ].join('');
  }

  /** Escape HTML special characters to prevent XSS. */
  function escapeHTML(str) {
    if (typeof str !== 'string') return '';
    return str
      .replace(/&/g,  '&amp;')
      .replace(/</g,  '&lt;')
      .replace(/>/g,  '&gt;')
      .replace(/"/g,  '&quot;')
      .replace(/'/g,  '&#39;');
  }

  /* ══════════════════════════════════════════════════════════════════
     PASSWORD SYSTEM
     Reads passwords from D.passwords (admin-control/other/passwords.js)
  ══════════════════════════════════════════════════════════════════ */

  /**
   * Unlock a password-gated section.
   * Called by the inline onclick on each unlock button.
   * @param {string} inputId   - ID of the <input type="password"> field
   * @param {string} sectionId - ID of the <div class="secret-content"> to reveal
   * @param {string} pwKey     - key in D.passwords (e.g. 'about', 'photos')
   */
  window.unlockSection = function (inputId, sectionId, pwKey) {
    var inputEl   = el(inputId);
    var sectionEl = el(sectionId);
    if (!inputEl || !sectionEl) return;

    var entered  = inputEl.value;
    var correct  = D.passwords[pwKey] || '';

    if (!correct) {
      /* No password set — just unlock */
      sectionEl.style.display = 'block';
      return;
    }

    if (entered === correct) {
      sectionEl.style.display = 'block';
      inputEl.closest('.inline-password-form') &&
        inputEl.closest('.inline-password-form').remove();
    } else {
      inputEl.value = '';
      inputEl.placeholder = 'Incorrect. Try again.';
      inputEl.style.borderColor = '#f87171';
      setTimeout(function () {
        inputEl.style.borderColor = '';
        inputEl.placeholder = 'password';
      }, 1800);
    }
  };

  /* ── Birthday unlock (special case — uses own key) ─────────────── */
  /* Keeps backward compat with older inline onclick in index.html */
  window.unlockBirthday = function () {
    window.unlockSection('bday-pw', 'bday-secret-info', 'birthday');
    /* Inject birth details after unlock */
    setTimeout(renderBirthdayDetails, 300);
  };

  /* ══════════════════════════════════════════════════════════════════
     HOMEPAGE — Hero section
  ══════════════════════════════════════════════════════════════════ */

  function renderHero() {
    var h = D.home || {};
    var n = D.heroName || {};

    /* Hero name — 3 word spans */
    var namePart1 = el('name-part-1');
    var namePart2 = el('name-part-2');
    var namePart3 = el('name-part-3');
    if (namePart1) namePart1.textContent = n.word1 || 'Manomay';
    if (namePart2) namePart2.textContent = n.word2 || 'Shailendra';
    if (namePart3) namePart3.textContent = n.word3 || 'Misra';

    /* Tagline */
    var taglineEl = el('hero-tagline');
    if (taglineEl) taglineEl.textContent = D.tagline || '';

    /* Nav hint — replaces {contactLink} with clickable <a> */
    var hintEl  = el('hero-nav-hint');
    var hintText = h.navHint || '';
    var hintLink = h.navHintLinkText || 'contact me';
    if (hintEl && hintText) {
      var linkHTML = '<a href="#" onclick="navigateTo(\'contact\'); return false;">'
                     + escapeHTML(hintLink) + '</a>';
      hintEl.innerHTML = hintText.replace('{contactLink}', linkHTML);
    }

    /* Hero photo */
    var heroImg = qs('.hero-photo');
    if (heroImg && D.heroPhoto) heroImg.src = D.heroPhoto;

    /* Footer */
    var footerLeft  = qs('.footer-left  .footer-desktop-only');
    var footerRight = qs('.footer-right .footer-desktop-only');
    if (footerLeft  && D.footerLeft)  footerLeft.textContent  = D.footerLeft;
    if (footerRight && D.footerRight) footerRight.textContent = D.footerRight;

    /* Scroll indicator label */
    var scrollLabel = qs('.scroll-indicator span');
    if (scrollLabel && h.scrollLabel) scrollLabel.textContent = h.scrollLabel;
  }

  function renderHeroLinks() {
    var links    = D.homeLinks || [];
    var container = qs('.hero-links');
    if (!container || !links.length) return;

    container.innerHTML = links.map(function (link) {
      return [
        '<a class="hero-link-item" href="#"',
          ' onclick="navigateTo(\'' + link.page + '\'); return false;">',
          '<span class="link-label">' + escapeHTML(link.label) + '</span>',
          '<span class="link-arrow">→</span>',
        '</a>'
      ].join('');
    }).join('');
  }

  /* ══════════════════════════════════════════════════════════════════
     IDENTITY PAGE
  ══════════════════════════════════════════════════════════════════ */

  function renderIdentity() {
    var ab = D.about || {};

    /* About photo */
    var aboutImg = qs('.about-photo');
    if (aboutImg && D.aboutPhoto) aboutImg.src = D.aboutPhoto;

    /* Photo caption */
    var caption = qs('.about-photo-label');
    if (caption && ab.photoCaption) caption.textContent = ab.photoCaption;

    /* Intro quote */
    var quote = qs('.about-intro');
    if (quote && ab.introQuote) quote.textContent = ab.introQuote;

    /* Body text — supports paragraphs split by \n\n */
    var bodyEl = el('about-text');
    if (bodyEl && ab.bodyText) {
      var paragraphs = ab.bodyText.split('\n\n');
      bodyEl.innerHTML = paragraphs.map(function (p) {
        return '<p>' + escapeHTML(p.trim()) + '</p>';
      }).join('');
    }

    /* Secret text */
    var secretEl = qs('#secret-about-content p');
    if (secretEl && ab.secretText) secretEl.textContent = ab.secretText;
  }

  /* ══════════════════════════════════════════════════════════════════
     CV / RESUME PAGE
  ══════════════════════════════════════════════════════════════════ */

  function renderResume() {
    var cv = D.resume || {};

    /* Name */
    var nameEl = qs('.resume-name');
    if (nameEl && cv.name) nameEl.innerHTML = escapeHTML(cv.name).replace('\n', '<br>');

    /* Title */
    var titleEl = qs('.resume-title');
    if (titleEl && cv.title) titleEl.textContent = cv.title;

    /* Contact block */
    var contactEl = qs('.resume-contact-col');
    if (contactEl && cv.contact && cv.contact.length) {
      contactEl.innerHTML = cv.contact.map(function (line) {
        return escapeHTML(line);
      }).join('<br>');
    }

    /* Summary */
    var summaryEl = qs('.resume-section p');
    if (summaryEl && cv.summary) summaryEl.textContent = cv.summary;

    /* Experience entries */
    var expSection = qs('.resume-section[data-section="experience"]');
    if (expSection && cv.experience && cv.experience.length) {
      var expHTML = cv.experience.map(function (entry) {
        return [
          '<div class="resume-entry">',
            '<div>',
              '<div class="resume-entry-title">' + escapeHTML(entry.title) + '</div>',
              '<div class="resume-entry-org">'   + escapeHTML(entry.org)   + '</div>',
              '<div class="resume-entry-desc">'  +
                escapeHTML(entry.desc || '').replace(/\n\n/g, '</div><div class="resume-entry-desc">') +
              '</div>',
            '</div>',
            '<div class="resume-entry-date">' + escapeHTML(entry.date) + '</div>',
          '</div>'
        ].join('');
      }).join('');
      expSection.innerHTML =
        '<div class="resume-section-title">Experience</div>' + expHTML;
    }

    /* Education entries */
    var eduSection = qs('.resume-section[data-section="education"]');
    if (eduSection && cv.education && cv.education.length) {
      var eduHTML = cv.education.map(function (entry) {
        return [
          '<div class="resume-entry">',
            '<div>',
              '<div class="resume-entry-title">' + escapeHTML(entry.title) + '</div>',
              '<div class="resume-entry-org">'   + escapeHTML(entry.org)   + '</div>',
            '</div>',
            '<div class="resume-entry-date">' + escapeHTML(entry.date) + '</div>',
          '</div>'
        ].join('');
      }).join('');
      eduSection.innerHTML =
        '<div class="resume-section-title">Education</div>' + eduHTML;
    }

    /* Skills */
    var skillsContainer = qs('.resume-skills');
    if (skillsContainer && cv.skills && cv.skills.length) {
      skillsContainer.innerHTML = cv.skills.map(function (skill) {
        return '<span class="skill-tag">' + escapeHTML(skill) + '</span>';
      }).join('');
    }

    /* PDF download link */
    var pdfLink = qs('.resume-download a');
    if (pdfLink && cv.pdfPath) pdfLink.href = cv.pdfPath;
  }

  /* ══════════════════════════════════════════════════════════════════
     PROFILES PAGE
  ══════════════════════════════════════════════════════════════════ */

  function renderProfiles() {
    var pr = D.profiles || {};
    var links = pr.links || [];
    var grid  = qs('.profiles-grid');
    if (!grid || !links.length) return;

    grid.innerHTML = links.map(function (link) {
      return [
        '<a class="profile-item" href="' + escapeHTML(link.url || '#') + '"',
          link.url && link.url !== '#' ? ' target="_blank" rel="noopener"' : '',
          '>',
          '<div class="profile-icon">' + (link.icon || '') + '</div>',
          '<div>',
            '<div class="profile-info-name">'   + escapeHTML(link.label  || '') + '</div>',
            link.handle
              ? '<div class="profile-info-handle">' + escapeHTML(link.handle) + '</div>'
              : '',
          '</div>',
          '<span class="profile-arrow">↗</span>',
        '</a>'
      ].join('');
    }).join('');
  }

  /* ══════════════════════════════════════════════════════════════════
     JOURNEY / TIMELINE PAGE
  ══════════════════════════════════════════════════════════════════ */

  /* Store years data for click handler */
  var _journeyYears = [];

  function renderJourney() {
    var jrn   = D.journey || {};
    var years = jrn.years || [];
    _journeyYears = years;

    var track = el('years-track');
    if (!track || !years.length) return;

    track.innerHTML = years.map(function (entry) {
      return [
        '<div class="year-node" data-year="' + entry.year + '"',
          ' onclick="MSM.openYear(' + entry.year + ')"',
          entry.hasContent ? ' data-has-content="true"' : '',
          '>',
          '<div class="year-dot"></div>',
          '<div class="year-label">' + entry.year + '</div>',
        '</div>'
      ].join('');
    }).join('');
  }

  /**
   * Open a year panel. Called by onclick on year nodes.
   * Also called by main.js click handler.
   */
  window.MSM = window.MSM || {};
  window.MSM.openYear = function (year) {
    var entry = _journeyYears.find(function (y) { return y.year === year; });
    if (!entry) return;

    /* Update active node */
    qsa('.year-node').forEach(function (n) { n.classList.remove('active'); });
    var node = qs('.year-node[data-year="' + year + '"]');
    if (node) node.classList.add('active');

    /* Populate detail panel */
    setText('detail-year',  entry.year);
    setText('detail-title', entry.title || '');
    var bodyEl = el('detail-body');
    if (bodyEl) {
      if (entry.hasContent && entry.body) {
        var paragraphs = entry.body.split('\n\n');
        bodyEl.innerHTML = paragraphs.map(function (p) {
          return '<p>' + escapeHTML(p.trim()) + '</p>';
        }).join('');
      } else {
        var placeholder = (D.journey || {}).emptyPlaceholder || 'Nothing recorded yet.';
        bodyEl.innerHTML = '<p style="color:var(--text3); font-style:italic;">'
                            + escapeHTML(placeholder) + '</p>';
      }
    }

    /* Show the panel */
    var detail = el('year-detail');
    if (detail) {
      detail.classList.add('visible');
    }
  };

  /* ══════════════════════════════════════════════════════════════════
     THOUGHTS / BELIEFS PAGE
  ══════════════════════════════════════════════════════════════════ */

  /* Store categories for openBelief / closeBelief */
  var _beliefCategories = [];

  function renderThoughts() {
    var th   = D.thoughts || {};
    var cats = th.categories || [];
    _beliefCategories = cats;

    var grid = qs('.beliefs-grid');
    if (!grid || !cats.length) return;

    grid.innerHTML = cats.map(function (cat) {
      var postCount = (cat.posts || []).length;
      return [
        '<div class="belief-card" onclick="openBelief(\'' + cat.id + '\')">',
          '<div class="belief-icon">' + (cat.icon || '') + '</div>',
          '<div class="belief-title">' + escapeHTML(cat.title || '') + '</div>',
          '<div class="belief-preview">' + escapeHTML(cat.preview || '') + '</div>',
          '<div class="belief-count">' + postCount + ' post' + (postCount === 1 ? '' : 's') + '</div>',
        '</div>'
      ].join('');
    }).join('');
  }

  /* Open a belief category — called by onclick */
  window.openBelief = function (categoryId) {
    var cat = _beliefCategories.find(function (c) { return c.id === categoryId; });
    if (!cat) return;

    /* Hide grid, show post view */
    var grid     = el('beliefs-overview');
    var postView = el('belief-post-view');
    if (grid)     grid.style.display = 'none';
    if (postView) {
      postView.classList.add('active');

      /* Set label */
      var labelEl = el('belief-view-label');
      if (labelEl) labelEl.textContent = cat.title || '';

      /* Build posts */
      var postsEl  = el('belief-posts-list');
      var posts    = cat.posts || [];
      if (postsEl) {
        postsEl.innerHTML = posts.length
          ? posts.map(function (post) {
              return [
                '<div class="belief-post">',
                  '<div class="belief-post-date">'  + escapeHTML(post.date  || '') + '</div>',
                  '<div class="belief-post-title">' + escapeHTML(post.title || '') + '</div>',
                  '<div class="belief-post-body">'  + escapeHTML(post.body  || '') + '</div>',
                '</div>'
              ].join('');
            }).join('')
          : '<p style="color:var(--text3);">No posts in this category yet.</p>';
      }
    }
  };

  window.closeBelief = function () {
    var grid     = el('beliefs-overview');
    var postView = el('belief-post-view');
    if (grid)     grid.style.display = '';
    if (postView) postView.classList.remove('active');
  };

  /* ══════════════════════════════════════════════════════════════════
     PHOTOS PAGE
  ══════════════════════════════════════════════════════════════════ */

  /* Store all albums for the viewer */
  var _currentAlbum  = null;
  var _currentPhoto  = 0;

  function renderPhotos() {
    renderAlbumGrid('public-albums',  D.publicAlbums  || []);
    renderAlbumGrid('secret-albums',  D.privateAlbums || []);
  }

  function renderAlbumGrid(containerId, albums) {
    var container = el(containerId);
    if (!container || !albums.length) return;

    container.innerHTML = albums.map(function (album) {
      var coverHTML = album.cover
        ? '<img src="' + escapeHTML(album.cover) + '" class="album-thumb" alt="' + escapeHTML(album.title) + '">'
        : '<div class="album-thumb-placeholder"><span style="font-size:2rem;color:var(--text3);">'
            + (album.icon || '🖼') + '</span></div>';

      return [
        '<div class="album-card" onclick="openAlbum(\'' + album.id + '\')">',
          coverHTML,
          '<div class="album-count">' + (album.count || 0) + ' photos</div>',
          '<div class="album-overlay">',
            '<div class="album-title">' + escapeHTML(album.title || '') + '</div>',
            '<div class="album-desc">'  + escapeHTML(album.desc  || '') + '</div>',
          '</div>',
        '</div>'
      ].join('');
    }).join('');
  }

  /* Open album viewer */
  window.openAlbum = function (albumId) {
    var allAlbums = (D.publicAlbums || []).concat(D.privateAlbums || []);
    var album = allAlbums.find(function (a) { return a.id === albumId; });
    if (!album) return;

    _currentAlbum = album;
    _currentPhoto = 0;

    var viewer = el('photo-viewer');
    if (!viewer) return;

    if (album.photos && album.photos.length) {
      showPhoto(0);
      viewer.classList.add('open');
    } else {
      /* No photos yet — show a message */
      var img = el('viewer-img');
      if (img) { img.src = ''; img.style.display = 'none'; }
      setText('viewer-title', album.title);
      setText('viewer-desc',  'No photos in this album yet.');
      viewer.classList.add('open');
    }
  };

  function showPhoto(index) {
    if (!_currentAlbum || !_currentAlbum.photos) return;
    var photos = _currentAlbum.photos;
    if (index < 0 || index >= photos.length) return;
    _currentPhoto = index;
    var photo = photos[index];
    var img   = el('viewer-img');
    if (img) { img.src = photo.src || ''; img.style.display = ''; }
    setText('viewer-title', photo.title || '');
    setText('viewer-desc',  photo.desc  || '');
  }

  window.closeViewer = function () {
    var viewer = el('photo-viewer');
    if (viewer) viewer.classList.remove('open');
    _currentAlbum = null;
    _currentPhoto = 0;
  };

  window.viewerNav = function (direction) {
    if (!_currentAlbum || !_currentAlbum.photos) return;
    var newIndex = _currentPhoto + direction;
    var len      = _currentAlbum.photos.length;
    /* Wrap around */
    if (newIndex < 0)   newIndex = len - 1;
    if (newIndex >= len) newIndex = 0;
    showPhoto(newIndex);
  };

  /* ══════════════════════════════════════════════════════════════════
     BIRTHDAY CLOCK PAGE
  ══════════════════════════════════════════════════════════════════ */

  var _birthdayInterval = null;

  function renderBirthdayDetails() {
    var bday = D.birthday || {};
    var secretEl = el('bday-secret-info');
    if (!secretEl) return;

    /* Calculate age */
    var today    = new Date();
    var birthYear = bday.birthYear || 2008;
    var age      = today.getFullYear() - birthYear;
    /* If birthday hasn't happened this year yet, subtract 1 */
    var monthDay  = bday.birthdayDate || 'August 29';
    var thisYearBday = new Date(today.getFullYear() + ' ' + monthDay);
    if (today < thisYearBday) age--;

    secretEl.innerHTML = [
      '<p><strong style="color:var(--text);">Date of Birth:</strong> ' +
        escapeHTML(monthDay) + ' ' + birthYear + '</p>',
      '<p><strong style="color:var(--text);">Time:</strong> ' +
        escapeHTML(bday.birthTime || '') + '</p>',
      '<p><strong style="color:var(--text);">Place:</strong> ' +
        escapeHTML(bday.birthPlace || '') + '</p>',
      '<p><strong style="color:var(--text);">Age:</strong> ' + age + '</p>',
    ].join('');
  }

  function startBirthdayTimer() {
    var bday = D.birthday || {};
    var monthDay = bday.birthdayDate || 'August 29';

    function tick() {
      var now  = new Date();
      var year = now.getFullYear();

      /* Find next birthday */
      var next = new Date(year + ' ' + monthDay);
      if (next <= now) next = new Date((year + 1) + ' ' + monthDay);

      var diff   = next - now;
      var days   = Math.floor(diff / 86400000);
      var hours  = Math.floor((diff % 86400000) / 3600000);
      var mins   = Math.floor((diff % 3600000)  / 60000);
      var secs   = Math.floor((diff % 60000)    / 1000);
      var ms     = diff % 1000;

      setText('bd-days',  String(days));
      setText('bd-hours', String(hours).padStart(2, '0'));
      setText('bd-mins',  String(mins).padStart(2, '0'));
      setText('bd-secs',  String(secs).padStart(2, '0'));
      var msEl = el('bd-ms');
      if (msEl) msEl.textContent = String(ms).padStart(3, '0') + ' ms';

      /* Check if today is the birthday — show wish */
      var isBirthday = (now.getMonth() === next.getMonth() - 1 &&
                        now.getDate()  === next.getDate() - 1) ||
                       (now.getDate() === new Date(year + ' ' + monthDay).getDate() &&
                        now.getMonth() === new Date(year + ' ' + monthDay).getMonth());
      var wishEl = qs('.birthday-wish-text');
      if (wishEl) {
        var isToday = (now.toDateString() === new Date(year + ' ' + monthDay).toDateString());
        wishEl.style.display = isToday ? 'inline-block' : 'none';
        if (isToday) wishEl.textContent = bday.wishText || '✦ Happy Birthday ✦';
      }
    }

    clearInterval(_birthdayInterval);
    tick();
    _birthdayInterval = setInterval(tick, 100);
  }

  /* ══════════════════════════════════════════════════════════════════
     LISTS PAGE (Curations)
  ══════════════════════════════════════════════════════════════════ */

  function renderLists() {
    var li = D.lists || {};
    renderListPanel('list-series', li.series  || []);
    renderListPanel('list-books',  li.books   || []);
    renderListPanel('list-places', li.places  || []);
    renderListPanel('list-movies', li.movies  || []);
  }

  function renderListPanel(panelId, items) {
    var panel = el(panelId);
    if (!panel) return;
    panel.innerHTML = items.map(function (item, i) {
      return buildListItem(i + 1, item.title, item.meta, item.status, item.label);
    }).join('');
  }

  /**
   * Switch between tabs on Lists or Projects pages.
   * Called by inline onclick on .list-tab elements.
   * @param {string} tabId   - panel ID suffix (e.g. 'series', 'completed')
   * @param {HTMLElement} el - the clicked tab element
   */
  window.switchListTab = function (tabId, clickedEl) {
    if (!clickedEl) return;
    var tabsContainer = clickedEl.parentElement;
    var pageSection   = tabsContainer ? tabsContainer.closest('.page') : null;

    /* Deactivate all tabs in this tab group */
    if (tabsContainer) {
      Array.from(tabsContainer.querySelectorAll('.list-tab')).forEach(function (t) {
        t.classList.remove('active');
      });
    }
    clickedEl.classList.add('active');

    /* Deactivate all panels in this page section */
    if (pageSection) {
      Array.from(pageSection.querySelectorAll('.list-panel')).forEach(function (p) {
        p.classList.remove('active');
      });
    }

    /* Activate the target panel */
    var targetPanel = el('list-' + tabId);
    if (targetPanel) targetPanel.classList.add('active');
  };

  /* ══════════════════════════════════════════════════════════════════
     PROJECTS PAGE
  ══════════════════════════════════════════════════════════════════ */

  function renderProjects() {
    var pj = D.projects || {};

    renderProjectPanel('list-completed', pj.completed || []);
    renderProjectPanel('list-working',   pj.working   || []);
    renderProjectPanel('list-abandoned', pj.abandoned || []);
  }

  function renderProjectPanel(panelId, items) {
    var panel = el(panelId);
    if (!panel) return;
    panel.innerHTML = items.map(function (item, i) {
      return buildListItem(i + 1, item.title, item.meta, item.status, item.label);
    }).join('');
  }

  /* ══════════════════════════════════════════════════════════════════
     GAMES PAGE
  ══════════════════════════════════════════════════════════════════ */

  function renderGames() {
    var ga = D.games || {};

    /* Public games */
    var publicGrid = qs('#page-games .games-grid');
    var pubGames   = ga.publicGames || [];
    if (publicGrid && pubGames.length) {
      publicGrid.innerHTML = pubGames.map(function (game) {
        return [
          '<div class="game-card" onclick="openGame(\'' + game.type + '\')">',
            '<div class="game-icon">' + (game.icon || '') + '</div>',
            '<div class="game-name">' + escapeHTML(game.name || '') + '</div>',
            '<div class="game-desc">' + escapeHTML(game.desc || '') + '</div>',
            '<div class="game-play-btn">▶ &nbsp; Play</div>',
          '</div>'
        ].join('');
      }).join('');
    }

    /* Private games */
    var privContent = el('private-games-content');
    var privGames   = ga.privateGames || [];
    if (privContent && privGames.length) {
      privContent.innerHTML = '<div class="games-grid">' +
        privGames.map(function (game) {
          var linkLabel = game.linkType === 'apk' ? '↓ &nbsp; Download APK' : '🔗 &nbsp; Play on GitHub';
          return [
            '<div class="game-card">',
              '<div class="game-icon">' + (game.icon || '') + '</div>',
              '<div class="game-name">' + escapeHTML(game.name || '') + '</div>',
              '<div class="game-desc">' + escapeHTML(game.desc || '') + '</div>',
              '<a href="' + escapeHTML(game.url || '#') + '"',
                ' target="_blank" rel="noopener"',
                ' class="game-play-btn" style="text-decoration:none;margin-top:auto;">',
                linkLabel,
              '</a>',
            '</div>'
          ].join('');
        }).join('') +
      '</div>';
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     SOCIAL PROOF PAGE
  ══════════════════════════════════════════════════════════════════ */

  function renderSocial() {
    var so = D.social || {};

    /* Logos marquee — duplicate for seamless loop */
    var logosTrack = qs('.logos-track');
    var logos      = so.logos || [];
    if (logosTrack && logos.length) {
      var logoHTML = logos.map(function (name) {
        return '<span class="logo-item">' + escapeHTML(name) + '</span>' +
               '<span class="logo-item">·</span>';
      }).join('');
      /* Duplicate for infinite scroll */
      logosTrack.innerHTML = logoHTML + logoHTML;
    }

    /* Testimonials */
    var testGrid = qs('.testimonials-grid');
    var tests    = so.testimonials || [];
    if (testGrid && tests.length) {
      testGrid.innerHTML = tests.map(function (t) {
        return [
          '<div class="testimonial-card">',
            '<div class="stars">' + '★'.repeat(t.stars || 5) + '</div>',
            '<div class="testimonial-text">'   + escapeHTML(t.text   || '') + '</div>',
            '<div class="testimonial-author">' + escapeHTML(t.author || '') + '</div>',
          '</div>'
        ].join('');
      }).join('');
    }
  }

  /* ══════════════════════════════════════════════════════════════════
     CONTACT PAGE — EmailJS setup
  ══════════════════════════════════════════════════════════════════ */

  function initEmailJS() {
    var ejsCfg = D.emailjs || {};
    if (ejsCfg.publicKey && window.emailjs) {
      window.emailjs.init(ejsCfg.publicKey);
    }
  }

  /**
   * Submit the contact form using EmailJS.
   * Called by the form's onsubmit attribute.
   */
  window.submitContactForm = function (event) {
    event.preventDefault();
    var form     = event.target;
    var statusEl = el('form-status');
    var ejsCfg   = D.emailjs || {};

    if (!ejsCfg.serviceId || !ejsCfg.templateId) {
      if (statusEl) {
        statusEl.textContent = 'Contact form not configured yet.';
        statusEl.className   = 'form-status error';
      }
      return;
    }

    if (statusEl) {
      statusEl.textContent = 'Sending...';
      statusEl.className   = 'form-status';
    }

    window.emailjs.sendForm(ejsCfg.serviceId, ejsCfg.templateId, form)
      .then(function () {
        if (statusEl) {
          statusEl.textContent = 'Message sent. I\'ll read it.';
          statusEl.className   = 'form-status success';
        }
        form.reset();
      })
      .catch(function (err) {
        console.error('[MSM Contact]', err);
        if (statusEl) {
          statusEl.textContent = 'Something went wrong. Try emailing directly.';
          statusEl.className   = 'form-status error';
        }
      });
  };

  /* ══════════════════════════════════════════════════════════════════
     SKILL BARS — animate when skills page is opened
  ══════════════════════════════════════════════════════════════════ */

  window.MSM.animateSkillBars = function () {
    qsa('.skill-item').forEach(function (item) {
      item.classList.add('animated');
    });
  };

  /* ══════════════════════════════════════════════════════════════════
     LAZY PAGE RENDERING
     Called by main.js (or sidebar-controller.js) when a page opens.
     Prevents rendering all 13 pages on first load.
  ══════════════════════════════════════════════════════════════════ */

  var _rendered = {}; /* track which pages have been rendered */

  /**
   * Render a specific page's dynamic content on first visit.
   * Call this from main.js in your page-open handler:
   *   MSM.renderPage(pageId);
   *
   * @param {string} pageId - matches data-page attribute on <section>
   */
  window.MSM.renderPage = function (pageId) {
    if (_rendered[pageId]) return; /* already done */
    _rendered[pageId] = true;

    switch (pageId) {
      case 'about'   : renderIdentity();   break;
      case 'resume'  : renderResume();     break;
      case 'profiles': renderProfiles();   break;
      case 'journey' : renderJourney();    break;
      case 'birthday': startBirthdayTimer(); break;
      case 'thoughts': renderThoughts();   break;
      case 'photos'  : renderPhotos();     break;
      case 'lists'   : renderLists();      break;
      case 'skills'  : window.MSM.animateSkillBars(); break;
      case 'games'   : renderGames();      break;
      case 'social'  : renderSocial();     break;
      case 'projects': renderProjects();   break;
    }
  };

  /* ══════════════════════════════════════════════════════════════════
     INIT — runs on DOMContentLoaded
     Homepage content always renders immediately.
     All other pages render lazily (on first visit).
  ══════════════════════════════════════════════════════════════════ */

  function init() {
    initEmailJS();
    renderHero();
    renderHeroLinks();

    /* Render the page that is currently active */
    var activePage = document.querySelector('.page.active[data-page]');
    if (activePage) {
      window.MSM.renderPage(activePage.dataset.page);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
