/* ═══════════════════════════════════════════════════════════════════
   admin-control/index.js
   ───────────────────────────────────────────────────────────────────
   THIS IS THE MASTER COMBINER FILE.
   DO NOT EDIT THIS FILE.
   ───────────────────────────────────────────────────────────────────
   WHAT THIS FILE DOES:
   Takes every window.ADMIN_* variable set by the other files in
   this folder and combines them into one single object:
   window.MSM_DATA

   Your website's data.js reads from window.MSM_DATA.
   ───────────────────────────────────────────────────────────────────
   LOAD ORDER IN INDEX.HTML (this file must be LAST):

   <script src="admin-control/other/settings.js"></script>
   <script src="admin-control/other/passwords.js"></script>
   <script src="admin-control/other/images.js"></script>
   <script src="admin-control/buttons/nav.js"></script>
   <script src="admin-control/buttons/home.js"></script>
   <script src="admin-control/pages/home.js"></script>
   <script src="admin-control/pages/identity.js"></script>
   <script src="admin-control/pages/cv.js"></script>
   <script src="admin-control/pages/social.js"></script>
   <script src="admin-control/pages/profiles.js"></script>
   <script src="admin-control/pages/journey.js"></script>
   <script src="admin-control/pages/photos.js"></script>
   <script src="admin-control/pages/thoughts.js"></script>
   <script src="admin-control/pages/lists.js"></script>
   <script src="admin-control/pages/games.js"></script>
   <script src="admin-control/pages/clock.js"></script>
   <script src="admin-control/pages/projects.js"></script>
   <script src="admin-control/index.js"></script>  ← ALWAYS LAST
═══════════════════════════════════════════════════════════════════ */

(function () {
  'use strict';

  /* ── Guard: if any ADMIN_ variable is missing, use empty object ──
     This prevents the whole site from crashing if one file fails.   */
  var S  = window.ADMIN_SETTINGS  || {};
  var PW = window.ADMIN_PASSWORDS || {};
  var IM = window.ADMIN_IMAGES    || {};
  var NV = window.ADMIN_NAV       || {};
  var HB = window.ADMIN_HOME_BUTTONS || {};

  var HO = window.ADMIN_HOME     || {};
  var ID = window.ADMIN_IDENTITY || {};
  var CV = window.ADMIN_CV       || {};
  var SO = window.ADMIN_SOCIAL   || {};
  var PR = window.ADMIN_PROFILES || {};
  var JR = window.ADMIN_JOURNEY  || {};
  var PH = window.ADMIN_PHOTOS   || {};
  var TH = window.ADMIN_THOUGHTS || {};
  var LI = window.ADMIN_LISTS    || {};
  var GA = window.ADMIN_GAMES    || {};
  var CL = window.ADMIN_CLOCK    || {};
  var PJ = window.ADMIN_PROJECTS || {};

  /* ── Build the unified MSM_DATA object ─────────────────────────── */
  window.MSM_DATA = {

    /* ── Site-level settings ── */
    site     : S.site     || {},
    emailjs  : S.emailjs  || {},
    behaviour: S.behaviour || {},

    /* ── Passwords ── */
    passwords: PW,

    /* ── Images & albums ── */
    images       : IM,
    publicAlbums : IM.publicAlbums  || [],
    privateAlbums: IM.privateAlbums || [],

    /* ── Navigation ── */
    nav          : NV,
    desktopLinks : NV.desktopLinks  || [],
    mobileLinks  : NV.mobileLinks   || [],
    sidebarLinks : NV.sidebarLinks  || [],
    homeLinks    : HB.links         || [],

    /* ── Page content ── */
    home    : HO,
    about   : ID,
    resume  : CV,
    social  : SO,
    profiles: PR,
    journey : JR,
    photos  : PH,
    thoughts: TH,
    lists   : LI,
    games   : GA,
    birthday: CL,
    projects: PJ,

    /* ── Flat shortcuts that data.js uses directly ────────────────── */
    heroName     : HO.heroName    || { word1: '', word2: '', word3: '' },
    tagline      : HO.tagline     || '',
    aboutText    : ID.bodyText    || '',
    secretAbout  : ID.secretText  || '',
    introQuote   : ID.introQuote  || '',
    heroLinks    : HB.links       || [],
    footerLeft   : HO.footerLeft  || '',
    footerRight  : HO.footerRight || '',

    /* ── Hero photo + about photo shortcuts ── */
    heroPhoto : IM.hero  || 'assets/photos/profilepic.jpeg',
    aboutPhoto: IM.about || 'assets/photos/stagepic.jpeg',

  };

  /* ── Console confirmation ───────────────────────────────────────── */
  var pages = ['home','about','resume','social','profiles',
               'journey','photos','thoughts','lists','games',
               'birthday','projects'];
  var loaded = pages.filter(function(p){ return !!window.MSM_DATA[p]; });
  console.log('[MSM] Admin data ready. Pages loaded: ' + loaded.join(', '));

})();
